package backend

// Calendar's AppleScript alarm delete handler fails even for a fresh writable
// event. Use EventKit only for display-alarm replacement, preserving the event and
// all other alarm types. Calendar still owns ordinary event targeting and fields.
func alarmScriptHandlers() []string {
	return []string{
		`use framework "EventKit"`,
		`on requireAlarmAccess()`,
		`if (current application's EKEventStore's authorizationStatusForEntityType:0) as integer is not 3 then error "Display-alarm changes require Full Access in System Settings > Privacy & Security > Calendars for the invoking app"`,
		`end requireAlarmAccess`,
		`on replaceDisplayAlarm(targetRef, calendarRef, reminderText, scopeText)`,
		`my requireAlarmAccess()`,
		`tell application "Calendar"`,
		`set targetUID to uid of targetRef as text`,
		`set calendarName to name of calendarRef as text`,
		`set startSeconds to my unixSeconds(start date of targetRef) as real`,
		`end tell`,
		`set store to current application's EKEventStore's alloc()'s init()`,
		`set matchingCalendars to {}`,
		`repeat with entry in (store's calendarsForEntityType:0)`,
		`set nativeCal to contents of entry`,
		`if (nativeCal's |title|() as text) is calendarName then set end of matchingCalendars to nativeCal`,
		`end repeat`,
		`if (count of matchingCalendars) is 0 then error "Alarm calendar not found in EventKit"`,
		`set fromDate to current application's NSDate's dateWithTimeIntervalSince1970:(startSeconds - 1)`,
		`set toDate to current application's NSDate's dateWithTimeIntervalSince1970:(startSeconds + 1)`,
		`set predicate to store's predicateForEventsWithStartDate:fromDate endDate:toDate calendars:matchingCalendars`,
		`set matches to {}`,
		`repeat with entry in (store's eventsMatchingPredicate:predicate)`,
		`set candidate to contents of entry`,
		`set candidateStart to candidate's startDate()`,
		`if (candidateStart's timeIntervalSince1970() as real) is startSeconds then`,
		`set internalID to candidate's calendarItemIdentifier() as text`,
		`set externalID to candidate's calendarItemExternalIdentifier()`,
		`if externalID is missing value then set externalID to ""`,
		`if internalID is targetUID or (externalID as text) is targetUID then set end of matches to candidate`,
		`end if`,
		`end repeat`,
		`if (count of matches) is not 1 then error "Alarm event identity is missing or ambiguous in EventKit; no alarm was changed"`,
		`set nativeEvent to item 1 of matches`,
		`my replaceAlarmValues(nativeEvent, reminderText)`,
		`set saveSpan to 0`,
		`if scopeText is "series" or scopeText is "future" then set saveSpan to 1`,
		`set {saved, saveError} to store's saveEvent:nativeEvent span:saveSpan |error|:(reference)`,
		`if not saved then error (saveError's localizedDescription() as text)`,
		`if not (nativeEvent's refresh() as boolean) then error "Alarm saved but event readback unavailable"`,
		`my verifyAlarmValues(nativeEvent, reminderText)`,
		`end replaceDisplayAlarm`,
		`on replaceAlarmValues(nativeEvent, reminderText)`,
		`set alarms to nativeEvent's alarms()`,
		`if alarms is not missing value then`,
		`repeat with entry in (alarms as list)`,
		`set alarmRef to contents of entry`,
		`if (alarmRef's |type|() as integer) is 0 then nativeEvent's removeAlarm:alarmRef`,
		`end repeat`,
		`end if`,
		`if reminderText is not "__ACAL_KEEP__" then`,
		`set newAlarm to current application's EKAlarm's alarmWithRelativeOffset:((reminderText as integer) * 60)`,
		`nativeEvent's addAlarm:newAlarm`,
		`end if`,
		`end replaceAlarmValues`,
		`on verifyAlarmValues(nativeEvent, reminderText)`,
		`set displayCount to 0`,
		`set alarms to nativeEvent's alarms()`,
		`if alarms is not missing value then`,
		`repeat with entry in (alarms as list)`,
		`set alarmRef to contents of entry`,
		`if (alarmRef's |type|() as integer) is 0 then`,
		`set displayCount to displayCount + 1`,
		`if reminderText is "__ACAL_KEEP__" then error "Display alarm remained after clearing"`,
		`if alarmRef's absoluteDate() is not missing value then error "Expected a relative display alarm"`,
		`if (alarmRef's relativeOffset() as real) is not ((reminderText as integer) * 60) then error "Display alarm offset was not saved"`,
		`end if`,
		`end repeat`,
		`end if`,
		`if reminderText is not "__ACAL_KEEP__" and displayCount is not 1 then error "Expected exactly one display alarm after replacement"`,
		`end verifyAlarmValues`,
	}
}
