#!/usr/bin/env python3
"""Render a Homebrew binary formula for a native-proof package directory."""

import argparse
import hashlib
import json
from pathlib import Path
import re
from urllib.parse import urlparse


def ruby_string(value):
    # Single-quoted Ruby strings have no interpolation; escape only slash/quote.
    return "'" + value.replace('\\', '\\\\').replace("'", "\\'") + "'"


def render(package_dir, base_url, revision):
    build = json.loads((package_dir / 'BUILD-INFO.json').read_text())
    if not re.fullmatch(r'[a-f0-9]{64}', build['source_sha256']):
        raise ValueError('invalid source hash in package manifest')
    if not re.fullmatch(r'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z', build['built_at']):
        raise ValueError('invalid build timestamp')
    if urlparse(base_url).scheme not in ('https', 'file'):
        raise ValueError('base URL must use https, or file for local qualification')
    if any(ord(c) < 32 for c in base_url):
        raise ValueError('base URL cannot contain control characters')
    stamp = re.sub(r'\D', '', build['built_at'])
    version = f"0.0.0-{stamp}.{build['source_sha256'][:12]}"
    archives = {}
    for arch in ('arm64', 'amd64'):
        name = f'acal-native-proof-darwin-{arch}.tar.gz'
        archives[arch] = (base_url.rstrip('/') + '/' + name,
                          hashlib.sha256((package_dir / name).read_bytes()).hexdigest())
    return f'''# Generated by scripts/native-proof-formula.py; experimental binary formula.
# This installs prebuilt archives, not a Homebrew-built bottle or cask.
class AcalNativeProof < Formula
  desc "Experimental EventKit integration for the acal CLI"
  homepage "https://github.com/agisilaos/acal"
  version {ruby_string(version)}
  revision {revision}
  license "MIT"

  depends_on :macos
  on_macos do
    depends_on macos: :sonoma
  end

  on_arm do
    url {ruby_string(archives['arm64'][0])}
    sha256 {ruby_string(archives['arm64'][1])}
  end
  on_intel do
    url {ruby_string(archives['amd64'][0])}
    sha256 {ruby_string(archives['amd64'][1])}
  end

  def install
    # Rename only the public executable; preserve its install-relative helper path.
    bin.install "bin/acal" => "acal-native-proof"
    libexec.install "libexec/acal-native.app"
    prefix.install "BUILD-INFO.json", "QUALIFICATION.txt"
  end

  def caveats
    <<~EOS
      Experimental native proof; production acal is unchanged.
      Run acal-native-proof native setup --json to check Calendar access.
      Only explicit native setup --request-access may prompt.
      Writes require an isolated --state-dir and only change owned fixtures.
      No production undo/redo. No notarization or Developer ID identity is used.
      Stable macOS/provider/launcher/upgrade qualification remains required.
    EOS
  end

  test do
    info = JSON.parse((prefix/"BUILD-INFO.json").read)
    assert_match info.fetch("version"), shell_output("#{{bin}}/acal-native-proof version")
    helper = libexec/"acal-native.app/Contents/MacOS/acal-native"
    request = {{ protocol: "unsupported", request_id: "a" * 32, operation: "add", args: {{}} }}
    result = JSON.parse(pipe_output(helper.to_s, JSON.generate(request), 0))
    assert_equal "rejected", result.fetch("outcome")
    assert_equal "PROTOCOL_ERROR", result.fetch("error").fetch("code")
  end
end
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--package-dir', required=True, type=Path)
    parser.add_argument('--base-url', help='HTTPS archive directory; defaults to local file URLs')
    parser.add_argument('--revision', type=int, default=0, help='Homebrew packaging revision')
    args = parser.parse_args()
    if args.revision < 0:
        parser.error('revision must be nonnegative')
    directory = args.package_dir.resolve(strict=True)
    print(render(directory, args.base_url or directory.as_uri(), args.revision), end='')


if __name__ == '__main__':
    main()
